FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install python3.7
RUN apt-get -y install python3-pip
RUN apt-get -y install nano vim git wget curl libsndfile1

